In [1]:
#Importando bibliotecas
import pandas as pd
import numpy as np
import random as r

In [2]:
#Lendo arquivos
df = pd.read_csv('3 - MetalForte_300_Registros.csv')
tec = pd.read_csv('tabela_tecnicos.csv', sep=';')

In [3]:
df

,ID_Registro,Data_Manutencao,Numero_OS,Maquina,Setor,Fabricante,Tipo_Manutencao,Tecnico,Especialidade,Hora_Inicio,Hora_Fim,Horas_Parada,Custo_Manutencao,Peca_Utilizada,Quantidade_Pecas,Causa_Falha,Status_OS,Observacao
0,1,2025-04-26,OS-1001,Prensa Hidraulica,Montagem,Bosch,Preventiva,NaN,Mecânico,10.1,9.9,-17.7,-701.11,Bomba,3,Falha elétrica,Aberta,NaN
1,2,17-02-2025,OS-1002,Prensa Hidraulica,Montagem,Siemens,Preditiva,NaN,Automação,1.6,16.8,-17.2,-11805.37,Bomba,7,Falha elétrica,Concluída,NaN
2,3,03/02/2025,OS-1003,Torno C N C,Montagem,WEG,Preditiva,NaN,Automação,14.1,15.9,-8.0,-9588.87,Filtro,8,Lubrificação,Em andamento,NaN
3,4,29-04-2025,OS-1004,Torno C N C,Usin.,Schneider,Preditiva,NaN,Automação,16.9,18.0,-3.4,-6849.24,Sensor,9,Falha mecânica,Em andamento,NaN
4,5,06-02-2025,OS-1005,Prensa Hidraulica,Usin.,Siemens,Preditiva,NaN,Mecânico,1.0,6.5,-7.6,-12967.13,Sensor,4,Falha mecânica,Concluída,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,2025-01-03,OS-1296,Fresadora CNC,Montagem,WEG,Preventiva,NaN,Mecânico,13.6,10.9,-4.5,-5389.72,Correia,6,Falha elétrica,Concluída,NaN
296,297,2025-01-13,OS-1297,Torno CNC,Usin.,Bosch,Preventiva,NaN,Automação,12.1,9.7,-16.2,-7589.60,Filtro,10,Lubrificação,Em andamento,NaN
297,298,16/01/2025,OS-1298,Torno CNC,Montagem,Schneider,Corretiva,NaN,Mecânico,8.3,9.2,-1.2,-5692.44,CLP,8,Desgaste,Concluída,NaN
298,299,2025-02-10,OS-1299,Corte Laser,Montagem,Bosch,Corretiva,NaN,Automação,13.5,3.2,-8.5,-1756.09,Bomba,6,Lubrificação,Aberta,NaN
299,300,21-05-2025,OS-1300,Compressor,Usin.,Fanuc,Preventiva,NaN,Eletricista,1.1,4.9,-12.2,-4779.24,Motor,5,Falha elétrica,Aberta,NaN

In [4]:
#Verificando quantidade de valores nulos
df.isnull().sum()

ID_Registro           0
Data_Manutencao       0
Numero_OS             0
Maquina               0
Setor                 0
Fabricante            0
Tipo_Manutencao       0
Tecnico             300
Especialidade         0
Hora_Inicio           0
Hora_Fim              0
Horas_Parada          0
Custo_Manutencao      0
Peca_Utilizada        0
Quantidade_Pecas      0
Causa_Falha           0
Status_OS             0
Observacao          300
dtype: int64

In [5]:
df.describe()

,ID_Registro,Tecnico,Hora_Inicio,Hora_Fim,Horas_Parada,Custo_Manutencao,Quantidade_Pecas,Observacao
count,300.000000,0.0,300.000000,300.000000,300.000000,300.000000,300.000000,0.0
mean,150.500000,NaN,11.065667,10.152000,-11.376000,-7427.995300,5.756667,NaN
std,86.746758,NaN,5.593916,5.258097,6.728874,4287.968278,3.027873,NaN
min,1.000000,NaN,1.000000,1.000000,-23.900000,-14980.450000,1.000000,NaN
25%,75.750000,NaN,6.200000,5.700000,-16.600000,-10858.582500,3.000000,NaN
50%,150.500000,NaN,11.350000,9.800000,-11.100000,-7250.015000,6.000000,NaN
75%,225.250000,NaN,15.825000,14.300000,-5.800000,-3870.462500,9.000000,NaN
max,300.000000,NaN,20.000000,20.000000,-0.600000,-143.520000,10.000000,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_Registro       300 non-null    int64
 1   Data_Manutencao   300 non-null    object
 2   Numero_OS         300 non-null    object
 3   Maquina           300 non-null    object
 4   Setor             300 non-null    object
 5   Fabricante        300 non-null    object
 6   Tipo_Manutencao   300 non-null    object
 7   Tecnico           0 non-null      float64
 8   Especialidade     300 non-null    object
 9   Hora_Inicio       300 non-null    float64
 10  Hora_Fim          300 non-null    float64
 11  Horas_Parada      300 non-null    float64
 12  Custo_Manutencao  300 non-null    float64
 13  Peca_Utilizada    300 non-null    object
 14  Quantidade_Pecas  300 non-null    int64
 15  Causa_Falha       300 non-null    object
 16  Status_OS         300 non-null    object
 17  Observacao        0 non-null      float64
dtypes: float64(6), int64(2), object(10)
memory usage: 42.3+ KB

In [7]:
#Removendo colunas desnecessárias
df.drop(['Hora_Inicio', 'Hora_Fim', 'Observacao', 'Tecnico'], axis=1, inplace=True)

In [8]:
df['Data_Manutencao']

0      2025-04-26
1      17-02-2025
2      03/02/2025
3      29-04-2025
4      06-02-2025
          ...
295    2025-01-03
296    2025-01-13
297    16/01/2025
298    2025-02-10
299    21-05-2025
Name: Data_Manutencao, Length: 300, dtype: object

In [9]:
#Normalizando as datas
df['Data_Manutencao'] = pd.to_datetime(df['Data_Manutencao'], format='mixed')

df['Data_Manutencao']

0     2025-04-26
1     2025-02-17
2     2025-03-02
3     2025-04-29
4     2025-06-02
         ...
295   2025-01-03
296   2025-01-13
297   2025-01-16
298   2025-02-10
299   2025-05-21
Name: Data_Manutencao, Length: 300, dtype: datetime64[ns]

In [10]:
#Normalizando o horário
df['Horas_Parada'] = df['Horas_Parada'] * -1

df['Horas_Parada'] = (
    pd.to_datetime('00:00:00')
    + pd.to_timedelta(df['Horas_Parada'], unit='h')
).dt.strftime('%H:%M')

In [11]:
df['Maquina'].unique()

array(['Prensa Hidraulica', 'Torno C N C', 'TornoCNC', 'Fresadora CNC',
       'Compressor', 'Esteira', 'Soldadora Robotizada', 'Dobradeira',
       'Prensa Hidráulica', 'Centro de Usinagem', 'Torno CNC', 'Injetora',
       'Corte Laser'], dtype=object)

In [12]:
#Normalizando valores
df['Maquina'] = np.where(df['Maquina'] == 'Torno C N C', 'Torno CNC', df['Maquina'])
df['Maquina'] = np.where(df['Maquina'] == 'TornoCNC', 'Torno CNC', df['Maquina'])
df['Maquina'] = np.where(df['Maquina'] == 'Prensa Hidraulica', 'Prensa Hidráulica', df['Maquina'])

df['Maquina'].unique()

array(['Prensa Hidráulica', 'Torno CNC', 'Fresadora CNC', 'Compressor',
       'Esteira', 'Soldadora Robotizada', 'Dobradeira',
       'Centro de Usinagem', 'Injetora', 'Corte Laser'], dtype=object)

In [13]:
#Convertendo valores para positivo
df['Custo_Manutencao'] = df['Custo_Manutencao'] * -1
df['Custo_Manutencao']

0        701.11
1      11805.37
2       9588.87
3       6849.24
4      12967.13
         ...
295     5389.72
296     7589.60
297     5692.44
298     1756.09
299     4779.24
Name: Custo_Manutencao, Length: 300, dtype: float64

In [14]:
#Trazendo valores aleatórios da tabela técnicos
id = tec['ID_Tecnico'].to_list()

df['ID_Tecnico'] = np.random.choice(id, size=len(df))

df = df.merge(
    tec[['ID_Tecnico', 'Nome_Tecnico', 'Especialidade']],
    on='ID_Tecnico',
    how='left'
)

In [15]:
df.to_excel('Metalforte_limpa.xlsx', index=False)